version: '2.1'

services:
  zoo1:
    network_mode: "host"
    image: zookeeper
    #restart: always
    hostname: zoo1
    #ports:
      #- 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=docker01:2888:3888;2181 server.2=docker01:2889:3889;2182 server.3=docker01:2890:3890;2183

  zoo2:
    network_mode: "host"
    image: zookeeper
    #restart: always
    hostname: zoo2
    #ports:
      #- 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=docker01:2888:3888;2181 server.2=docker01:2889:3889;2182 server.3=docker01:2890:3890;2183

  zoo3:
    network_mode: "host"
    image: zookeeper
    #restart: always
    hostname: zoo3
    #ports:
      #- 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=docker01:2888:3888;2181 server.2=docker01:2889:3889;2182 server.3=docker01:2890:3890;2183